teslamotors/fixed-containers

- BUILD.bazel
- include/fixed_containers/enum_map.hpp
- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/pair_view.hpp
- test/enum_map_test.cpp
- test/fixed_map_test.cpp
- test/pair_view_test.cpp
This matches std::map's behavior
https://github.com/teslamotors/fixed-containers/issues/9
> Make iterators of FixedMap/EnumMap dereference to a non-assignable type

- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/fixed_set.hpp
- include/fixed_containers/fixed_vector.hpp
- test/fixed_map_test.cpp
- test/fixed_set_test.cpp
- test/fixed_vector_test.cpp
Add functions `make_fixed_map`, `make_fixed_set` and `make_fixed_vector` to deduce the size of their container at compile time.
When it's known that a container won't need to grow at runtime, it is now possible to create the container without specifying its maximum size, and its maximum size will be deduced to be the number of items passed to the `make_fixed_[map/set/vector]` function.
The `SIZE` template parameter in these functions has been pushed down as far as possible to make it possible to change other template parameters without having to specify the size.
Before:
```cpp
FixedVector<int, 3> vector{1, 2, 3};
```
After:
```cpp
auto v = make_fixed_vector<int>({1, 2, 3});
```
And now even the type can be deduced:
```cpp
auto v = make_fixed_vector({1, 2, 3});
```
> Add size deduction for FixedMap, FixedSet & FixedVector

- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/fixed_set.hpp
- include/fixed_containers/fixed_vector.hpp
- test/fixed_map_test.cpp
- test/fixed_set_test.cpp
- test/fixed_vector_test.cpp
This is done to comform with the std API that does not have these members.
> Remove full() members. Introduce is_full() free functions instead

- test/enum_map_test.cpp
- test/fixed_map_test.cpp
Specifically, the assignment `s_copy = s;` doesn't work, because it's trying to use the assignment operator of a pair where one of the members has reference type. Classes with reference members have their assignment operators defaulted as deleted.
> libc++ doesn't support `std::map<int, const int&>`

- BUILD.bazel
- include/fixed_containers/bidirectional_iterator.hpp
- include/fixed_containers/enum_map.hpp
- include/fixed_containers/enum_set.hpp
- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/fixed_red_black_tree.hpp
- include/fixed_containers/fixed_red_black_tree_nodes.hpp
- include/fixed_containers/fixed_red_black_tree_storage.hpp
- include/fixed_containers/fixed_red_black_tree_view.hpp
- include/fixed_containers/fixed_set.hpp
- include/fixed_containers/fixed_vector.hpp
- include/fixed_containers/index_range_predicate_iterator.hpp
- include/fixed_containers/iterator_utils.hpp
- include/fixed_containers/random_access_iterator_transformer.hpp
- test/fixed_map_perf_test.cpp
- test/fixed_red_black_tree_test.cpp
- test/fixed_red_black_tree_view_test.cpp
- test/index_range_predicate_iterator_test.cpp
Representing forward/backward, const/mutable, and red/black doesn't require magic enum machinery. This also removes the need for the repeated "msvc WORKAROUND," as far as I can tell (but please check me on that).
> Remove magic-enum dependency from everything except the enum containers

- include/fixed_containers/fixed_red_black_tree_view.hpp
- include/fixed_containers/iterator_utils.hpp
- include/fixed_containers/random_access_iterator_transformer.hpp
- test/fixed_map_test.cpp
- test/fixed_set_test.cpp
- test/fixed_vector_test.cpp
This is three commits: new tests (without changing behavior), better operators (without _observably_ changing behavior, and unrelated to the new tests), and then an ambitious change to the C++20 iterator-concept machinery (which does change behavior, reflected in the new tests). Each one could be taken upstream independently from any of the others, if you like.
> Some tweaks to RandomAccessIteratorTransformer

- .bazelrc
- CMakeLists.txt
Before this patch, Clang trunk gives:
[  2%] Building CXX object CMakeFiles/string_literal_test.dir/test/string_literal_test.cpp.o
error: include location '/usr/local/include' is unsafe for cross-compilation
[-Werror,-Wpoison-system-directories]
1 error generated.
Better would be to replace -Weverything with -Wall -Wextra (https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/)
> Clang: Add -Wno-poison-system-directories

- .bazelrc
- BUILD.bazel
- CMakeLists.txt
- include/fixed_containers/arrow_proxy.hpp
- include/fixed_containers/bidirectional_iterator.hpp
- include/fixed_containers/enum_map.hpp
- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/index_range_predicate_iterator.hpp
- include/fixed_containers/pair_view.hpp
- test/enum_map_test.cpp
- test/fixed_map_test.cpp
- test/pair_view_test.cpp
Currently, `FixedMap` and `EnumMap` return a `PairView<const K, const V>&` (notably, a reference in contrast to a value) in order to be able to support the same syntax that `std::map` does when iterating, i.e.:
```cpp
for (auto&& pair : map) {} // a
for (const auto& pair : map) {} // b
for (auto& pair : map) {} // c
```
However, this makes it possible for dangling references to occur.
```cpp
decltype(m)::reference ref = *m.begin(); // Dangling // 1
auto ref = *m.begin();  // Fine // 2
auto& ref = *m.begin();  // Dangling // 3
```
(all 3 are fine for `std::map`).
Problems:
1) Cannot store a `std::pair<const K, V>` because it is not assignable and not trivially copyable, so it is not possible to give a reference to it. Also, for `EnumMap` the key is not even stored, so there is no pair at …
> [FixedMap/EnumMap] Fix dangling references by changing iter return type

- CMakeLists.txt
- include/fixed_containers/enum_map.hpp
- test/enum_map_test.cpp
- test/pair_test.cpp
clang defines the __GNUC__,__GNUC_MINOR__, __GNUC_PATCHLEVEL__ macros, but they are hardcoded to version 4.2.1 and do not reflect the real version of libstdc++.
Instead, use _GLIBCXX_RELEASE. This allows proper libstdc++ version detection when compiling with clang (and using gcc libs)
> Use _GLIBXX_RELEASE instead of __GNUC__ to detect version of libstdc++

- include/fixed_containers/enum_map.hpp
- include/fixed_containers/fixed_vector.hpp
- test/enum_map_test.cpp
- test/enum_set_test.cpp
- test/fixed_map_test.cpp
- test/fixed_set_test.cpp
- test/fixed_vector_test.cpp
Aliases don't work here, use a forwarding child class.
https://en.cppreference.com/w/cpp/language/adl
https://en.cppreference.com/w/cpp/language/class_template_argument_deduction
> Fix FixedVector and EnumMap to work with ADL and CTAD

- CMakeLists.txt
Make the CMakeLists.txt more friendly if magic_enum is already in the project.
> Skip finding magic_enum package if the target exists

- include/fixed_containers/enum_utils.hpp
- test/enum_utils_test.cpp
- test/enums_test_common.hpp
```C++
enum class TestRichEnum1BackingEnum : std::uint32_t
{
C_ONE = 19,
C_FOUR = 25,
C_TWO = 21,
C_THREE = 23,
};
static_assert(TestRichEnum1::C_ONE().ordinal() == 0);
static_assert(TestRichEnum1::C_TWO().ordinal() == 1);
static_assert(TestRichEnum1::C_THREE().ordinal() == 2);
static_assert(TestRichEnum1::C_FOUR().ordinal() == 3);
static_assert(TestRichEnum1::value_of(19) == TestRichEnum1::C_ONE());
static_assert(TestRichEnum1::value_of(21) == TestRichEnum1::C_TWO());
static_assert(TestRichEnum1::value_of(23) == TestRichEnum1::C_THREE());
static_assert(TestRichEnum1::value_of(25) == TestRichEnum1::C_FOUR());
static_assert(TestRichEnum1::value_of(29) == std::nullopt);
```
> [SkeletalRichEnum] Fix ordinal() and value_of(underlying_int)

- include/fixed_containers/enum_array.hpp
- include/fixed_containers/enum_map.hpp
- include/fixed_containers/enum_set.hpp
- include/fixed_containers/fixed_circular_deque.hpp
- include/fixed_containers/fixed_circular_queue.hpp
- include/fixed_containers/fixed_deque.hpp
- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/fixed_queue.hpp
- include/fixed_containers/fixed_set.hpp
- include/fixed_containers/fixed_stack.hpp
- include/fixed_containers/fixed_string.hpp
- include/fixed_containers/fixed_vector.hpp
A `static_assert` causes a compilation failures for any utility
that was trying to check if this type is a tuple (e.g. via concepts).
Setting tuple_size to 0 is sufficient for preventing structured binding;
remove the `static_assert`
https://github.com/teslamotors/fixed-containers/issues/94
> Improve disabling of structured binding to be metaprogramming friendly 

- include/fixed_containers/algorithm.hpp
- include/fixed_containers/fixed_deque.hpp
- include/fixed_containers/fixed_vector.hpp
- test/fixed_circular_deque_test.cpp
- test/fixed_deque_test.cpp
- test/fixed_list_test.cpp
- test/fixed_vector_test.cpp
Also rename `emplace_move_backward` to `uninitialized_relocate_backward`, introduce (forward) `uninitialized_relocate`, and complete the circle by resuming the use of `uninitialized_relocate` in `erase`.
> [FixedVector] Fix double-destroy bug in `erase`

- WORKSPACE
- patches/benchmark_as_system_include.patch
https://github.com/google/benchmark/pull/1803
```
In file included from test/fixed_map_perf_test.cpp:4:
bazel-out/k8-fastbuild/bin/external/com_google_benchmark/_virtual_includes/benchmark_main/benchmark/benchmark.h:1801:25: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
1801 |           memory_result(NULL),
|                         ^~~~
|                         nullptr
/usr/lib/llvm-17/lib/clang/17/include/stddef.h:84:18: note: expanded from macro 'NULL'
84 | #    define NULL __null
|                  ^
In file included from test/fixed_map_perf_test.cpp:4:
bazel-out/k8-fastbuild/bin/external/com_google_benchmark/_virtual_includes/benchmark_main/benchmark/benchmark.h:378:7: error: 'MemoryManager' has no out-of-line virtual method definitions; its vtable …
```
> Fix benchmark builds for bazel

- include/fixed_containers/fixed_circular_deque.hpp
- include/fixed_containers/fixed_deque.hpp
- include/fixed_containers/fixed_list.hpp
- include/fixed_containers/fixed_map.hpp
- include/fixed_containers/fixed_set.hpp
- include/fixed_containers/fixed_unordered_map.hpp
- include/fixed_containers/fixed_unordered_set.hpp
- include/fixed_containers/fixed_vector.hpp
- test/fixed_circular_deque_test.cpp
- test/fixed_deque_test.cpp
- test/fixed_list_test.cpp
- test/fixed_map_test.cpp
- test/fixed_set_test.cpp
- test/fixed_unordered_map_test.cpp
- test/fixed_unordered_set_test.cpp
- test/fixed_vector_test.cpp
This is to allow users to specify such containers without needing to special-case on the client-side. As an exmaple, this can happen with conditionally populated entries from macros or codegen
> Special case make_fixed_*() for 0 parameters

- include/fixed_containers/random_access_iterator.hpp
- include/fixed_containers/random_access_iterator_transformer.hpp
- test/fixed_circular_deque_test.cpp
- test/fixed_deque_test.cpp
- test/fixed_string_test.cpp
- test/fixed_vector_test.cpp
Exposed by https://github.com/teslamotors/fixed-containers/issues/128
This was previously building without issue due to two-phase lookup and the function never being called. New units tests will instantiate this function.
```C++
template <class T>
struct MockTemplate
{
int foo(const MockTemplate<T>& input) const { return input.variable_that_does_not_exist; }
};
int main()
{
MockTemplate<int> it{};
(void)it;
// it.foo(it);
}
```
> [RandomAccessIterator] Fix reference to non-existent member

- include/fixed_containers/optional_reference.hpp
- test/optional_reference_test.cpp
This ctor exists for std::optional
> [OptionalReference] introduce OptionalReference(std::nullopt_t)

- include/fixed_containers/fixed_doubly_linked_list.hpp
- include/fixed_containers/fixed_index_based_storage.hpp
- test/fixed_map_test.cpp
- test/fixed_unordered_map_test.cpp
I ran some benchmarks on different clear options:
1) just `try_emplace` into the new map
2) the process in this PR (including the scary-looking memcopy)
3) the process in this PR used for constexpr contexts (no memcopy)
The above graph was created with a "fresh" map, starting empty and then pushing each element once. This means the linked list is in perfect order so we don't see the locality issues of using linked lists. Instead, I generated a "used" linked list by repeatedly deleting and replacing subsets of the array, yielding the following results:
> Fixed unordered map clear

- .clang-tidy
- test/fixed_map_perf_test.cpp
This is auto-ignored for structured bindings, but not for loops. A frequent use of this is for perf tests with google benchmark
> [clang-tidy] Ignore identifier `_` which expresses an unused variable

- CMakeLists.txt
Ensures we are compatible with other compilers
Also makes it consistent with the bazel build
> [CMake] Use -std=c++20 instead of -std=gnu++20

- include/fixed_containers/struct_view.hpp
- test/struct_view_test.cpp
If the path does not resolve to reflected field data, return `false` from `add_path` so that callers can properly handle error conditions.
> Allow error handling from StructView::add_path

- CMakeLists.txt
Lower versions generate a build file that doesn't build any files without an obvious error
> Bump required CMake version to 3.21 (from 3.16)

- include/fixed_containers/concepts.hpp
It is not needed as of C++20, but older clang versions are failing. Fixes build for clang <=16
> Add explicit deduction guide for Overloaded

- vcpkg.json
0.9.7 changes <magic_enum.hpp> to <magic_enum/magic_enum.hpp>
> [vcpkg] Temporarily pin magic_enum to 0.9.6 to fix CI

- include/fixed_containers/enum_set.hpp
- include/fixed_containers/fixed_set_adapter.hpp
- test/enum_set_test.cpp
- test/fixed_set_test.cpp
- test/fixed_unordered_set_test.cpp
- Missing const in FixedSetAdapter
- Missing find() implementation in `EnumSet
> [Sets] Add unit tests for find() and fix uncovered issues

- include/fixed_containers/optional_reference.hpp
- test/optional_reference_test.cpp
This adds a constructor to `OptionalReference` that allows creating references from pointer types.
> [OptionalReference] Add pointer constructor

- include/fixed_containers/fixed_index_based_storage.hpp
- include/fixed_containers/wyhash.hpp
- test/fixed_red_black_tree_view_test.cpp
- test/string_literal_test.cpp
By replacing unsafe functions with safe alternatives and 1 suppression
> Fix -Wunsafe-buffer-usage-in-libc-call issues
